// Generated from IconSprite.astro. Keep in sync when you add a symbol.
export const ICON_NAMES = [
  "arrow-down",
  "arrow-up",
  "audit",
  "bookmark",
  "bot",
  "check",
  "chev-down",
  "chev-left",
  "chev-right",
  "chev-up",
  "dashboard",
  "dots",
  "download",
  "external",
  "filters",
  "globe",
  "help",
  "inbox",
  "info",
  "link",
  "menu",
  "message",
  "moon",
  "plus",
  "save",
  "search",
  "settings",
  "sparkles",
  "sun",
  "trend",
  "user",
  "warn",
  "x",
] as const;

export type IconName = (typeof ICON_NAMES)[number];
